### ISSUE TITLE
Plugin: Amiga Boing and Roaches

### ISSUE THREAD

**Issue by Eignar17** [matijaskala/compiz-snow#1]
update plugins ported to compiz 0.8 please:
http://forum.compiz.org/viewtopic.php?f=89&t=8668&hilit=Roach
http://forum.compiz.org/viewtopic.php?f=89&t=8662&p=60183&hilit=boing#p60183

@matijaskala

**Comment by matijaskala** [comment]
Done
- https://github.com/matijaskala/compiz-boing
- https://github.com/matijaskala/compiz-roach
